### ISSUE TITLE
User Themes

### ISSUE THREAD

**Issue by ceuk** [ceuk/spotui#22]
Using the existing patterns in [config.py](https://github.com/ceuk/spotui/blob/master/spotui/src/config.py) and [colors.py](https://github.com/ceuk/spotui/blob/master/spotui/src/colors.py) implement a new config section: "theme" that allows users to define the terminal color using the ncurses constant names. These config values should be plugged into colors.py (replacing the hardcoded values) if they are present.

e.g.

```toml
[theme]
progress_bar_fg = "COLOR_GREEN"
progress_bar_bg = "COLOR_BLACK"
border_fg = "COLOR_WHITE"
border_bg = "COLOR_BLACK"
border_active_fg = "COLOR_YELLOW"
# ...etc
```

We will also need to define a set of themeable colors as currently the colors file and use thereof isn't very organised (Basically, we need to make sure that we have a pair defined for each semantic UI element: e.g. progress bar etc - and that we update the pairs being used by these elements accordingly)
